//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellerAcunMedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProject
    {
        public int ProjectID { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string GitHubUrl { get; set; }
        public string Title { get; set; }
    }
}
