//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellerAcunMedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSocialMedia
    {
        public int SocialMediaID { get; set; }
        public string SocialMediaName { get; set; }
        public string Url { get; set; }
        public string IconUrl { get; set; }
    }
}
